import {} from "./controller/projectController.js"
import {} from "./views/headerView.js"
import {} from "./views/projectListView.js"
import {} from "./views/newProjectLightbox.js"
import {} from "./views/currentProjectView.js"
import {} from "./views/newTaskLightbox.js"
import {} from "./views/editTaskLightbox.js"
import {} from "./views/currentFilterView.js"